title: Minimal theme
logo: /assets/img/WhatsApp Image 2021-10-22 at 7.29.06 PM.jpeg
description: Minimal is a theme for GitHub Pages.
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
